spring:
  profiles:
    active: local
  datasource:
    driver-class-name: ${mygo.datasource.driver-class-name}
    url: jdbc:mysql://${mygo.datasource.host}:${mygo.datasource.port}/${mygo.datasource.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: ${mygo.datasource.username}
    password: ${mygo.datasource.password}
  data:
    redis:
      host: ${mygo.data.redis.host}
      port: ${mygo.data.redis.port}

  mail:
    host: smtp.163.com
    username: a728076618@163.com
    password: mpw:jyLRm9mWq9o6tXAOYLefQtmFm/TH40oZX8K1eD5Fxy0=
    default-encoding: UTF-8

  jackson:
    time-zone: Asia/Shanghai # 或者 GMT+8



logging:
  level:
    com.mygo: debug


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler # 枚举类处理器
  global-config:
    db-config:
      id-type: auto # id自增
  mapper-locations: classpath*:/mapper/**/*.xml




mygo:
  jwt:
    location: classpath:mygo.jks # hs256密钥对
    store-password: mygomygo # jks文件的密码
    key-password: mygomygo #
    alias: mygo
    tokenTTL: 7d
  project-info:
    project-name: MYGO心理服务平台
    version: v1.0

