spring:
  profiles:
    active: local
  datasource:
    driver-class-name: ${mygo.datasource.driver-class-name}
    url: jdbc:mysql://${mygo.datasource.host}:${mygo.datasource.port}/${mygo.datasource.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: ${mygo.datasource.username}
    password: ${mygo.datasource.password}
logging:
  level:
    com.mygo: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

mygo:
  jwt:
    location: classpath:mygo.jks
    store-password: mpw:/4VrGA1afDwyytMgtd2NIg==
    key-password: mpw:/4VrGA1afDwyytMgtd2NIg==
    alias: mygo
    tokenTTL: 1h
